### PR TITLE
update py version to 1.3.0

### PR DESCRIPTION
**Pull request by andermi**

### CODE REVIEW

**Comment by hamilton8415** [comment]
OK, sorry I missed this previously.  I believe all other use of the version number take it straight from the top-level Cmake file (except for the actual github tag, which is done manually). I'm not sure if that's practical in this case, but it's easy enough to change this manually when things update.

**Comment by andermi** [comment]
I could probably do some cmake magic to auto populate the version in the setup.cfg

**Comment by hamilton8415** [comment]
As you like, I'm not sure it's worth going to far out of the way.  I'm not recalling exactly how it all works, but currently the CMake version makes its way into an config.h via a file via config.h.in.  Also, Cpack is used to make the debians and includes the version number in the filenames.

**Comment by andermi** [comment]
That oughta do it

**Pull request merged**
