### PR TITLE
start adding python bindings with pybind11

### PR DESCRIPTION
**Pull request by andermi**
need to grab a few things for python build:
```
$ sudo apt update
$ sudo apt install python3-build python3-wheel python3-venv python3-virtualenv python3-pybind11
```

build c++ with python binding flag
```
$ mkdir build
$ cd build
$ cmake -DBUILD_PYTHON_BINDINGS=ON ..
$ make
```

```
$ cd ../fshd_py
$ python3 -m build --wheel
```
Then you can either install and use it:
```
$ pip3 install dist/*.whl
$ fshd_motion_example
```
Or, you can try it out before installing (this method will also work after installing). If not installing, you will need to
install python prerequisites:

```
$ sudo apt update
$ sudo apt install python3-numpy python3-scipy python3-matplotlib
$ pip3 install ode
```
Then,
```
$ python3 -m fshd.examples.motion
```

added command line options from example as well (use -h to check)
```
$ fshd_motion_example -h
usage: fshd_motion_example [-h] [-a A] [-t T] [-p P] [-b B]

options:
  -h, --help  show this help message and exit
  -a A        (meters) sets the incident wave amplitude
  -t T        (seconds) sets the incident wave period
  -p P        (degrees) sets the incident wave phase angle
  -b B        (degrees) sets the incident wave direction
```

All available examples:
```
$ python3 -m fshd.examples.buoyancyforce
$ python3 -m fshd.examples.excitingforce
$ python3 -m fshd.examples.gravityforce
$ python3 -m fshd.examples.incidentwave
$ python3 -m fshd.examples.motion
$ python3 -m fshd.examples.plotcoeffs
$ python3 -m fshd.examples.radiationforce
```
Or,
```
fshd_buoyancyforce_example
fshd_excitingforce_example
fshd_gravityforce_example
fshd_incidentwave_example
fshd_motion_example
fshd_plotcoeffs_example
fshd_radiationforce_example
```

### CODE REVIEW

**Comment by andermi** [comment]
@hamilton8415 I finished binding the `LinearIncidentWave` and `FS_HydroDynamics` classes. I also ported `MotionExample.cpp` to python using the new module.

need to grab a few things for python build:
```
$ sudo apt update
$ sudo apt install python3-build python3-wheel python3-venv python3-virtualenv python3-pybind11
```

build c++ with python binding flag
```
$ mkdir build
$ cd build
$ cmake -DBUILD_PYTHON_BINDINGS=ON ..
$ make
```

```
$ cd ../fshd_py
$ python3 -m build --wheel
```
Then you can either install and use it:
```
$ pip3 install dist/*.whl
$ fshd_motion_example
```
Or, you can try it out before installing (this method will also work after installing)
```
$ python3 -m fshd.examples.motion
```

**Comment by andermi** [comment]
now you can choose to turn python bindings on (off by default) with
`cmake -DBUILD_PYTHON_BINDINGS=ON ..`

**Comment by andermi** [comment]
two more examples:

```
$ python3 -m fshd.examples.incidentwave
$ python3 -m fshd.examples.excitingforce
```

**Comment by andermi** [comment]
all examples added

**Comment by andermi** [comment]
added readme

**Comment by andermi** [comment]
check this out! Found something I could just drop your incident wave class into (like 10 lines of code)
using the python bindings
```
$ pip3 install pyglet configparser
$ tar -xvzf pabennett_ocean.tar.gz
$ cd pabennett_ocean
$ python3 main.py
```
[pabennett_ocean.tar.gz](https://github.com/hamilton8415/FreeSurfaceHydrodynamics/files/11327903/pabennett_ocean.tar.gz)

**Comment by hamilton8415** [comment]
Fantastic!  Cool it was easy, I want to look more closely into how this is implemented.   We will at some point in the future need to add the concept of multi-directional waves to this library, I have some ideas on how, more or less the incident wave stuff won't change, it'll just be a new incident wave object for each wave direction, but then they need to get summed up in the fs-hydro calculations.  Basically an array of inc_wave objects will need to be passed to the fs-hydro calc routines instead of a single one, those are passed as unique_ptrs I believe.  Not for the moment, but I'm mentioning it here in case it impacts your thinking on the python side.
 Looks like things are getting close to done for this.  I ran the various examples and they plot out nicely.

Is it practical to make building the python stuff the default instead of adding "-DBUILD_PYTHON_BINDINGS=ON".  Seems we may as well, although I'm not sure about the implications on the install side.

Probably when I merge this in I'll push the version number from 1.2.x to 1.3.0, but suggestions welcome.

Thanks!  Amazing job.

**Comment by andermi** [comment]
> make building the python stuff the default

done!

> array of inc_wave objects will need to be passed to the fs-hydro calc routines

Shouldn't be a problem for the bindings.

Glad you like it; it was really fun to do :) I hadn't used pybind11 before (I always used boost.python) but I know it's pretty popular and I can see why. They made it super easy and it doesn't have the bloat of boost (or the really convoluted compiler errors).

**Review by hamilton8415 — APPROVED** [review]
This runs nicely, thanks for doing it.

**Comment by hamilton8415** [comment]
Merging

**Pull request merged**
